import { useEffect, useMemo, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { fetchAuditLog, fetchIncidents, updateIncident, IncidentRecord, AuditEvent } from '../lib/dataApi';
import { cn } from '../lib/utils';

const statuses = [
  { key: 'Open', label: 'เปิดประเด็น', icon: 'fa-solid fa-circle-exclamation', tone: 'rose' },
  { key: 'In Progress', label: 'กำลังดำเนินการ', icon: 'fa-solid fa-person-running', tone: 'amber' },
  { key: 'Resolved', label: 'รอตรวจสอบ', icon: 'fa-solid fa-wand-magic-sparkles', tone: 'sky' },
  { key: 'Verified', label: 'ยืนยันแล้ว', icon: 'fa-solid fa-circle-check', tone: 'emerald' },
] as const;
type StatusKey = typeof statuses[number]['key'];
const toneClass = (tone: string, active = true) => !active ? 'border-slate-100 bg-slate-50 text-slate-300' : tone === 'rose' ? 'border-rose-100 bg-rose-600 text-white' : tone === 'amber' ? 'border-amber-100 bg-amber-500 text-white' : tone === 'sky' ? 'border-sky-100 bg-sky-600 text-white' : 'border-emerald-100 bg-emerald-600 text-white';

export default function IncidentDetail() {
  const { id } = useParams();
  const navigate = useNavigate();
  const [incident, setIncident] = useState<IncidentRecord | null>(null);
  const [history, setHistory] = useState<AuditEvent[]>([]);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');
  const [statusReason, setStatusReason] = useState('');
  const [verifiedBy, setVerifiedBy] = useState('');

  const load = () => Promise.all([fetchIncidents(), fetchAuditLog()]).then(([items, events]) => { setIncident(items.find(item => item.id === id) || null); setHistory(events.filter(event => event.incident_id === id)); }).catch(() => setError('ไม่สามารถโหลดรายละเอียด Incident ได้')).finally(() => setLoading(false));
  useEffect(() => { load(); }, [id]);
  const current = (incident?.resolution_status || 'Open') as StatusKey;
  const currentIndex = statuses.findIndex(status => status.key === current);
  const nextStatus = currentIndex < statuses.length - 1 ? statuses[currentIndex + 1].key : null;
  const statusHistory = useMemo(() => history.flatMap(event => Object.entries(event.changes || {}).filter(([key]) => key === 'resolution_status').map(([_, change]) => ({ event, change: change as { old: unknown; new: unknown } }))).sort((a, b) => new Date(a.event.edited_at).getTime() - new Date(b.event.edited_at).getTime()), [history]);
  const changeStatus = async (status: StatusKey) => {
    if (!incident || !nextStatus || status !== nextStatus) return;
    if (statusReason.trim().length < 3) { setError('กรุณาระบุเหตุผลการเปลี่ยนสถานะอย่างน้อย 3 ตัวอักษร'); return; }
    if (status === 'Verified' && !verifiedBy.trim()) { setError('กรุณาระบุชื่อผู้ตรวจสอบก่อนยืนยัน'); return; }
    setSaving(true); setError('');
    try { const updated = await updateIncident(incident.id, { resolution_status: status, status_reason: statusReason.trim(), verified_by: verifiedBy.trim() || undefined }); setIncident(updated); setStatusReason(''); setVerifiedBy(''); setNotice(`อัปเดตสถานะเป็น ${statuses.find(item => item.key === status)?.label} แล้ว`); await load(); } catch (err: any) { setError(err?.message || 'ไม่สามารถอัปเดตสถานะได้ กรุณาลองใหม่'); } finally { setSaving(false); }
  };
  if (loading) return <div className="space-y-5"><div className="skeleton h-5 w-32" /><div className="skeleton h-12 w-2/3" /><div className="skeleton h-64 w-full" /></div>;
  if (!incident) return <div className="rounded-2xl border border-rose-200 bg-rose-50 p-8 text-center"><i className="fa-solid fa-file-circle-xmark text-3xl text-rose-500" /><h2 className="mt-3 text-xl font-bold text-rose-900">ไม่พบ Incident รายการนี้</h2><Link to="/data" className="mt-5 inline-flex primary-button">กลับไปรายการความเสี่ยง</Link></div>;
  const caseEvents = [{ label: 'บันทึกเหตุการณ์', date: incident.created_at, icon: 'fa-solid fa-file-circle-plus', done: true }, ...statusHistory.map(item => ({ label: `เปลี่ยนสถานะเป็น ${String(item.change.new)}`, date: item.event.edited_at, icon: 'fa-solid fa-arrows-rotate', done: true })), ...(current !== 'Verified' ? [{ label: 'รอการดำเนินการถัดไป', date: '', icon: 'fa-solid fa-hourglass-half', done: false }] : [])];
  return <div className="space-y-6">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><Link to="/data" className="text-xs font-semibold text-maroon-700 hover:underline"><i className="fa-solid fa-arrow-left mr-2" />รายการความเสี่ยง</Link><p className="mt-4 font-mono text-xs font-bold uppercase tracking-[.16em] text-slate-400">Case Management</p><h2 className="mt-1 break-all text-2xl font-bold tracking-tight text-slate-950 sm:text-3xl">Incident #{incident.id.slice(0, 8).toUpperCase()}</h2><div className="mt-2 flex flex-wrap items-center gap-2 text-sm text-slate-500"><span>{incident.group_type || 'Incident'}</span><span>·</span><span>ระดับ {incident.impact_level || '-'}</span><span>·</span><span className="font-semibold text-maroon-700">{statuses[currentIndex]?.label}</span></div></div><button onClick={() => navigate('/data')} className="rounded-xl border border-slate-200 px-4 py-2.5 text-xs font-bold text-slate-600 transition hover:border-maroon-200 hover:bg-maroon-50 hover:text-maroon-700"><i className="fa-solid fa-pen mr-2" />แก้ไขข้อมูล</button></div>
    {(error || notice) && <div className={cn('rounded-xl border px-4 py-3 text-sm font-medium', error ? 'border-rose-200 bg-rose-50 text-rose-800' : 'border-emerald-200 bg-emerald-50 text-emerald-800')} role="status"><i className={cn('mr-2', error ? 'fa-solid fa-circle-exclamation' : 'fa-solid fa-circle-check')} />{error || notice}</div>}
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-maroon-700">Resolution lifecycle</p><h3 className="mt-1 text-xl font-bold text-slate-900">Open → In Progress → Resolved → Verified</h3></div><span className="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-bold text-slate-700">ขั้นที่ {currentIndex + 1} / 4</span></div><div className="mt-8 grid grid-cols-4 gap-2">{statuses.map((status, index) => <div key={status.key} className="relative text-center"><div className={cn('mx-auto flex h-11 w-11 items-center justify-center rounded-full border-4 text-sm', toneClass(status.tone, index <= currentIndex))}>{index < currentIndex ? <i className="fa-solid fa-check" /> : <i className={status.icon} />}</div>{index < statuses.length - 1 && <div className={cn('absolute left-[calc(50%+25px)] right-[calc(-50%+25px)] top-5 h-1 rounded-full', index < currentIndex ? 'bg-maroon-500' : 'bg-slate-100')} />}<p className={cn('mt-3 text-[11px] font-bold sm:text-xs', index <= currentIndex ? 'text-slate-800' : 'text-slate-400')}>{status.label}</p></div>)}</div><div className="mt-8 grid gap-3 rounded-xl bg-slate-50 p-4 sm:grid-cols-2"><label className="text-xs font-bold text-slate-600">เหตุผลการเปลี่ยนสถานะ<input value={statusReason} onChange={e => setStatusReason(e.target.value)} placeholder="เช่น เริ่มวิเคราะห์สาเหตุราก" className="mt-1 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm font-normal outline-none focus:border-maroon-500 focus:ring-2 focus:ring-maroon-500/10" /></label>{nextStatus === 'Verified' && <label className="text-xs font-bold text-slate-600">ผู้ตรวจสอบ / ผู้อนุมัติ<input value={verifiedBy} onChange={e => setVerifiedBy(e.target.value)} placeholder="ชื่อผู้ตรวจสอบ" className="mt-1 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm font-normal outline-none focus:border-maroon-500 focus:ring-2 focus:ring-maroon-500/10" /></label>}<div className="flex flex-wrap items-center justify-between gap-3 sm:col-span-2"><p className="text-xs text-slate-500">ระบบไม่อนุญาตให้ข้ามสถานะ และต้องมีเหตุผลทุกครั้ง</p>{nextStatus && <button onClick={() => changeStatus(nextStatus)} disabled={saving} className="primary-button text-xs">{saving ? <i className="fa-solid fa-spinner fa-spin" /> : <i className="fa-solid fa-arrow-right" />} {saving ? 'กำลังอัปเดต...' : `ไปยัง ${statuses.find(item => item.key === nextStatus)?.label}`}</button>}</div></div></section>
    <section className="grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><p className="text-xs font-bold uppercase tracking-[.16em] text-maroon-700">Case overview</p><h3 className="mt-1 text-xl font-bold text-slate-900">ข้อมูลเหตุการณ์</h3><div className="mt-6 grid gap-4 sm:grid-cols-2">{[['รายการความเสี่ยง', incident.risk_items?.join(', ') || incident.other_risk_item || '-'], ['ระดับผลกระทบ', incident.impact_level || '-'], ['หน่วยงานที่เกิดเหตุ', incident.causing_department || '-'], ['ผู้รับผิดชอบ', incident.responsible_person || '-'], ['กำหนดติดตาม (SLA)', incident.target_resolution_date || '-'], ['Resolved at', incident.resolved_at ? new Date(incident.resolved_at).toLocaleString('th-TH') : 'ยังไม่ปิดประเด็น'], ['Verified at', incident.verified_at ? new Date(incident.verified_at).toLocaleString('th-TH') : 'ยังไม่ผ่านการตรวจสอบ'], ['ผู้ตรวจสอบ', incident.verified_by || 'ยังไม่มี'], ['รายละเอียด', incident.incident_details], ['การแก้ไขเบื้องต้น', incident.initial_response], ['แนวทางปฏิบัติ', incident.guideline]].map(([label, value]) => <div key={label} className="rounded-xl bg-slate-50 p-4 sm:col-span-2"><p className="text-[11px] font-bold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 whitespace-pre-wrap text-sm leading-6 text-slate-700">{value}</p></div>)}</div></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><p className="text-xs font-bold uppercase tracking-[.16em] text-maroon-700">Case timeline</p><h3 className="mt-1 text-xl font-bold text-slate-900">ประวัติการดำเนินการ</h3><div className="mt-6">{caseEvents.map((event, index) => <div key={`${event.label}-${index}`} className="relative flex gap-4 pb-7"><div className={cn('relative z-10 flex h-9 w-9 shrink-0 items-center justify-center rounded-full', event.done ? 'bg-maroon-50 text-maroon-700' : 'bg-slate-100 text-slate-400')}><i className={event.icon} />{index < caseEvents.length - 1 && <span className="absolute left-1/2 top-9 h-full w-px -translate-x-1/2 bg-slate-200" />}</div><div><p className={cn('text-sm font-bold', event.done ? 'text-slate-800' : 'text-slate-400')}>{event.label}</p><p className="mt-1 text-xs text-slate-400">{event.date ? new Date(event.date).toLocaleString('th-TH') : 'ดำเนินการเมื่อพร้อม'}</p></div></div>)}</div></div></section>
  </div>;
}
