import { useEffect, useMemo, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { fetchAuditLog, fetchIncidents, updateIncident, IncidentRecord, AuditEvent } from '../lib/dataApi';
import { cn } from '../lib/utils';

export default function IncidentDetail() {
  const { id } = useParams();
  const navigate = useNavigate();
  const [incident, setIncident] = useState<IncidentRecord | null>(null);
  const [history, setHistory] = useState<AuditEvent[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');

  const load = () => Promise.all([fetchIncidents(), fetchAuditLog()]).then(([items, events]) => { setIncident(items.find(item => item.id === id) || null); setHistory(events.filter(event => event.incident_id === id)); }).catch(() => setError('ไม่สามารถโหลดรายละเอียด Incident ได้')).finally(() => setLoading(false));
  useEffect(() => { load(); }, [id]);
  if (loading) return <div className="space-y-5"><div className="skeleton h-5 w-32" /><div className="skeleton h-12 w-2/3" /><div className="skeleton h-64 w-full" /></div>;
  if (!incident) return <div className="rounded-2xl border border-rose-200 bg-rose-50 p-8 text-center"><i className="fa-solid fa-file-circle-xmark text-3xl text-rose-500" /><h2 className="mt-3 text-xl font-bold text-rose-900">ไม่พบ Incident รายการนี้</h2><Link to="/data" className="mt-5 inline-flex primary-button">กลับไปรายการความเสี่ยง</Link></div>;
  const caseEvents = [{ label: 'บันทึกเหตุการณ์', date: incident.created_at, icon: 'fa-solid fa-file-circle-plus', done: true }, ...(incident.assigned_at ? [{ label: 'มอบหมายผู้รับผิดชอบ', date: incident.assigned_at, icon: 'fa-solid fa-user-check', done: true }] : []), ...(incident.in_progress_at ? [{ label: 'เริ่มดำเนินการ', date: incident.in_progress_at, icon: 'fa-solid fa-person-running', done: true }] : [])];
  return <div className="space-y-6">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><Link to="/data" className="text-xs font-semibold text-maroon-700 hover:underline"><i className="fa-solid fa-arrow-left mr-2" />รายการความเสี่ยง</Link><p className="mt-4 font-mono text-xs font-bold uppercase tracking-[.16em] text-slate-400">Case Management</p><h2 className="mt-1 break-all text-2xl font-bold tracking-tight text-slate-950 sm:text-3xl">Incident #{incident.id.slice(0, 8).toUpperCase()}</h2><div className="mt-2 flex flex-wrap items-center gap-2 text-sm text-slate-500"><span>{incident.group_type || 'Incident'}</span><span>·</span><span>ระดับ {incident.impact_level || '-'}</span></div></div><button onClick={() => navigate('/data')} className="rounded-xl border border-slate-200 px-4 py-2.5 text-xs font-bold text-slate-600 transition hover:border-maroon-200 hover:bg-maroon-50 hover:text-maroon-700"><i className="fa-solid fa-pen mr-2" />แก้ไขข้อมูล</button></div>
    {(error || notice) && <div className={cn('rounded-xl border px-4 py-3 text-sm font-medium', error ? 'border-rose-200 bg-rose-50 text-rose-800' : 'border-emerald-200 bg-emerald-50 text-emerald-800')} role="status"><i className={cn('mr-2', error ? 'fa-solid fa-circle-exclamation' : 'fa-solid fa-circle-check')} />{error || notice}</div>}

    <section className="grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><p className="text-xs font-bold uppercase tracking-[.16em] text-maroon-700">Case overview</p><h3 className="mt-1 text-xl font-bold text-slate-900">ข้อมูลเหตุการณ์</h3><div className="mt-6 grid gap-4 sm:grid-cols-2">{[['รายการความเสี่ยง', incident.risk_items?.join(', ') || incident.other_risk_item || '-'], ['ระดับผลกระทบ', incident.impact_level || '-'], ['หน่วยงานที่เกิดเหตุ', incident.causing_department || '-'], ['ผู้รับผิดชอบ', incident.responsible_person || '-'], ['รายละเอียด', incident.incident_details], ['การแก้ไขเบื้องต้น', incident.initial_response], ['แนวทางปฏิบัติ', incident.guideline]].map(([label, value]) => <div key={label} className="rounded-xl bg-slate-50 p-4 sm:col-span-2"><p className="text-[11px] font-bold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 whitespace-pre-wrap text-sm leading-6 text-slate-700">{value}</p></div>)}</div></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><p className="text-xs font-bold uppercase tracking-[.16em] text-maroon-700">Case timeline</p><h3 className="mt-1 text-xl font-bold text-slate-900">ประวัติการดำเนินการ</h3><div className="mt-6">{caseEvents.map((event, index) => <div key={`${event.label}-${index}`} className="relative flex gap-4 pb-7"><div className={cn('relative z-10 flex h-9 w-9 shrink-0 items-center justify-center rounded-full', event.done ? 'bg-maroon-50 text-maroon-700' : 'bg-slate-100 text-slate-400')}><i className={event.icon} />{index < caseEvents.length - 1 && <span className="absolute left-1/2 top-9 h-full w-px -translate-x-1/2 bg-slate-200" />}</div><div><p className={cn('text-sm font-bold', event.done ? 'text-slate-800' : 'text-slate-400')}>{event.label}</p><p className="mt-1 text-xs text-slate-400">{event.date ? new Date(event.date).toLocaleString('th-TH') : 'ดำเนินการเมื่อพร้อม'}</p></div></div>)}</div></div></section>
  </div>;
}
