import { useEffect, useMemo, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { fetchAuditLog, fetchIncidents, updateIncident, IncidentRecord, AuditEvent } from '../lib/dataApi';
import { cn } from '../lib/utils';

const statuses = [
  { key: 'Open', label: 'เปิดประเด็น', icon: 'fa-solid fa-circle-exclamation', color: 'rose' },
  { key: 'In Progress', label: 'กำลังดำเนินการ', icon: 'fa-solid fa-person-running', color: 'amber' },
  { key: 'Resolved', label: 'รอตรวจสอบ', icon: 'fa-solid fa-wand-magic-sparkles', color: 'sky' },
  { key: 'Verified', label: 'ยืนยันแล้ว', icon: 'fa-solid fa-circle-check', color: 'emerald' },
] as const;

type StatusKey = typeof statuses[number]['key'];
export default function IncidentDetail() {
  const { id } = useParams();
  const navigate = useNavigate();
  const [incident, setIncident] = useState<IncidentRecord | null>(null);
  const [history, setHistory] = useState<AuditEvent[]>([]);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');
  useEffect(() => { Promise.all([fetchIncidents(), fetchAuditLog()]).then(([items, events]) => { setIncident(items.find(item => item.id === id) || null); setHistory(events.filter(event => event.incident_id === id)); }).catch(() => setError('ไม่สามารถโหลดรายละเอียด Incident ได้')).finally(() => setLoading(false)); }, [id]);
  const current = (incident?.resolution_status || 'Open') as StatusKey;
  const currentIndex = statuses.findIndex(status => status.key === current);
  const nextStatus = currentIndex < statuses.length - 1 ? statuses[currentIndex + 1].key : null;
  const incidentHistory = useMemo(() => history.flatMap(event => Object.entries(event.changes || {}).filter(([key]) => key === 'resolution_status').map(([_, change]) => ({ ...event, change: change as { old: unknown; new: unknown } }))).sort((a, b) => new Date(a.edited_at).getTime() - new Date(b.edited_at).getTime()), [history]);
  const changeStatus = async (status: StatusKey) => { if (!incident || status === current) return; setSaving(true); setError(''); try { const updated = await updateIncident(incident.id, { resolution_status: status }); setIncident(updated); setNotice(`อัปเดตสถานะเป็น ${statuses.find(item => item.key === status)?.label} แล้ว`); } catch { setError('ไม่สามารถอัปเดตสถานะได้ กรุณาลองใหม่'); } finally { setSaving(false); } };
  if (loading) return <div className="space-y-5"><div className="skeleton h-5 w-32" /><div className="skeleton h-12 w-2/3" /><div className="skeleton h-64 w-full" /></div>;
  if (!incident) return <div className="rounded-2xl border border-rose-200 bg-rose-50 p-8 text-center"><i className="fa-solid fa-file-circle-xmark text-3xl text-rose-500" /><h2 className="mt-3 text-xl font-bold text-rose-900">ไม่พบ Incident รายการนี้</h2><Link to="/data" className="mt-5 inline-flex primary-button">กลับไปรายการความเสี่ยง</Link></div>;
  return <div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><Link to="/data" className="text-xs font-semibold text-maroon-700 hover:underline"><i className="fa-solid fa-arrow-left mr-2" />รายการความเสี่ยง</Link><p className="mt-4 font-mono text-xs font-bold uppercase tracking-[.16em] text-slate-400">Incident Detail</p><h2 className="mt-1 break-all text-2xl font-bold tracking-tight text-slate-950 sm:text-3xl">{incident.id}</h2><p className="mt-1 text-sm text-slate-500">{incident.risk_type} · {incident.group_type} · {new Date(`${incident.incident_date}T00:00:00`).toLocaleDateString('th-TH')}</p></div><div className="flex gap-2"><button onClick={() => navigate('/data')} className="rounded-xl border border-slate-200 px-4 py-2.5 text-xs font-bold text-slate-600 transition hover:border-maroon-200 hover:bg-maroon-50 hover:text-maroon-700"><i className="fa-solid fa-pen mr-2" />แก้ไขข้อมูล</button></div></div>{(error || notice) && <div className={cn('rounded-xl border px-4 py-3 text-sm font-medium', error ? 'border-rose-200 bg-rose-50 text-rose-800' : 'border-emerald-200 bg-emerald-50 text-emerald-800')} role="status"> <i className={cn('mr-2', error ? 'fa-solid fa-circle-exclamation' : 'fa-solid fa-circle-check')} />{error || notice}</div>}
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-maroon-700">Resolution lifecycle</p><h3 className="mt-1 text-xl font-bold text-slate-900">ติดตามการปิดประเด็น</h3></div><span className={cn('rounded-full px-3 py-1.5 text-xs font-bold', current === 'Verified' ? 'bg-emerald-100 text-emerald-700' : current === 'Resolved' ? 'bg-sky-100 text-sky-700' : current === 'In Progress' ? 'bg-amber-100 text-amber-700' : 'bg-rose-100 text-rose-700')}>{statuses[currentIndex].label}</span></div><div className="mt-8 grid grid-cols-4 gap-2">{statuses.map((status, index) => <div key={status.key} className="relative text-center"><div className={cn('mx-auto flex h-11 w-11 items-center justify-center rounded-full border-4 text-sm transition', index <= currentIndex ? status.color === 'rose' ? 'border-rose-100 bg-rose-600 text-white' : status.color === 'amber' ? 'border-amber-100 bg-amber-500 text-white' : status.color === 'sky' ? 'border-sky-100 bg-sky-600 text-white' : 'border-emerald-100 bg-emerald-600 text-white' : 'border-slate-100 bg-slate-50 text-slate-300')}>{index < currentIndex ? <i className="fa-solid fa-check" /> : <i className={status.icon} />}</div>{index < statuses.length - 1 && <div className={cn('absolute left-[calc(50%+25px)] right-[calc(-50%+25px)] top-5 h-1 rounded-full', index < currentIndex ? 'bg-maroon-500' : 'bg-slate-100')} />}<p className={cn('mt-3 text-[11px] font-bold sm:text-xs', index <= currentIndex ? 'text-slate-800' : 'text-slate-400')}>{status.label}</p></div>)}</div><div className="mt-8 flex flex-wrap items-center justify-between gap-3 rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-500">เปลี่ยนได้ตามลำดับ เพื่อให้การปิดประเด็นมีหลักฐานตรวจสอบ</p>{nextStatus && <button onClick={() => changeStatus(nextStatus)} disabled={saving} className="primary-button text-xs">{saving ? <i className="fa-solid fa-spinner fa-spin" /> : <i className="fa-solid fa-arrow-right" />} {saving ? 'กำลังอัปเดต...' : `ไปยัง ${statuses.find(item => item.key === nextStatus)?.label}`}</button>}</div></section>
    <section className="grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><p className="text-xs font-bold uppercase tracking-[.16em] text-maroon-700">Case overview</p><h3 className="mt-1 text-xl font-bold text-slate-900">ข้อมูลเหตุการณ์</h3><div className="mt-6 grid gap-4 sm:grid-cols-2">{[['รายการความเสี่ยง', incident.risk_items?.join(', ') || incident.other_risk_item || '-'], ['ระดับผลกระทบ', incident.impact_level || '-'], ['หน่วยงานที่เกิดเหตุ', incident.causing_department || '-'], ['ผู้รับผิดชอบ', incident.responsible_person || '-'], ['รายละเอียด', incident.incident_details], ['การแก้ไขเบื้องต้น', incident.initial_response], ['แนวทางปฏิบัติ', incident.guideline]].map(([label, value]) => <div key={label} className="rounded-xl bg-slate-50 p-4 sm:col-span-2"><p className="text-[11px] font-bold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 whitespace-pre-wrap text-sm leading-6 text-slate-700">{value}</p></div>)}</div></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><p className="text-xs font-bold uppercase tracking-[.16em] text-maroon-700">Case timeline</p><h3 className="mt-1 text-xl font-bold text-slate-900">ประวัติการดำเนินการ</h3><div className="mt-6 space-y-0">{[{ label: 'บันทึกเหตุการณ์', date: incident.created_at, icon: 'fa-solid fa-file-circle-plus', done: true }, ...incidentHistory.map(event => ({ label: `เปลี่ยนสถานะเป็น ${String(event.change.new)}`, date: event.edited_at, icon: 'fa-solid fa-arrows-rotate', done: true })), ...(current !== 'Verified' ? [{ label: 'รอการดำเนินการถัดไป', date: '', icon: 'fa-solid fa-hourglass-half', done: false }] : [])].map((event, index, list) => <div key={`${event.label}-${index}`} className="relative flex gap-4 pb-7"><div className={cn('relative z-10 flex h-9 w-9 shrink-0 items-center justify-center rounded-full', event.done ? 'bg-maroon-50 text-maroon-700' : 'bg-slate-100 text-slate-400')}><i className={event.icon} />{index < list.length - 1 && <span className="absolute left-1/2 top-9 h-full w-px -translate-x-1/2 bg-slate-200" />}</div><div><p className={cn('text-sm font-bold', event.done ? 'text-slate-800' : 'text-slate-400')}>{event.label}</p><p className="mt-1 text-xs text-slate-400">{event.date ? new Date(event.date).toLocaleString('th-TH') : 'ดำเนินการเมื่อพร้อม'}</p></div></div>)}</div>{!incidentHistory.length && <p className="mt-2 text-xs text-slate-400">ประวัติการเปลี่ยนสถานะจะแสดงที่นี่เมื่อมีการอัปเดต</p>}</div></section>
  </div>;
}
