import { useState } from 'react';

const KEY = 'lab-incident-notification-settings';
const defaults = { enabled: true, notifyNearMiss: true, notifyMiss: true, notifyNoHarm: false };
function load() { try { return { ...defaults, ...JSON.parse(localStorage.getItem(KEY) || '{}') }; } catch { return defaults; } }
export default function NotificationSettings() {
  const [settings, setSettings] = useState(load);
  const update = (key: keyof typeof defaults) => setSettings(prev => { const next = { ...prev, [key]: !prev[key] }; localStorage.setItem(KEY, JSON.stringify(next)); return next; });
  return <div className="max-w-3xl space-y-6"><header><p className="text-xs font-semibold uppercase tracking-[.18em] text-maroon-700">System preferences</p><h2 className="mt-2 text-3xl font-bold tracking-tight text-slate-950">การแจ้งเตือน</h2><p className="mt-1 text-sm text-slate-500">กำหนดเหตุการณ์ที่ต้องการส่งแจ้งเตือนไปยัง Telegram โดยไม่ต้องเปิดเผย token</p></header><section className="space-y-2 rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-100">{([['enabled','เปิดใช้งานการแจ้งเตือน'],['notifyNearMiss','แจ้งเตือน Near Miss'],['notifyMiss','แจ้งเตือน Miss'],['notifyNoHarm','แจ้งเตือน No Harm']] as [keyof typeof defaults,string][]).map(([key,label]) => <button key={key} onClick={() => update(key)} className="flex w-full items-center justify-between rounded-xl p-4 text-left transition hover:bg-slate-50"><span><b className="block text-sm text-slate-800">{label}</b><small className="text-xs text-slate-400">การตั้งค่านี้จัดเก็บเฉพาะในอุปกรณ์นี้</small></span><span className={`relative h-6 w-11 rounded-full transition ${settings[key] ? 'bg-maroon-600' : 'bg-slate-200'}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white shadow transition ${settings[key] ? 'left-6' : 'left-1'}`} /></span></button>)}</section><p className="rounded-xl bg-amber-50 p-4 text-xs leading-relaxed text-amber-800">หมายเหตุ: ระบบยังคงบันทึกข้อมูลลง Google Sheets ตามปกติ การตั้งค่านี้มีผลเฉพาะการส่ง Telegram หลังบันทึกสำเร็จ</p></div>;
}
