import { useEffect, useState } from 'react';
import { fetchIncidents } from '../lib/dataApi';

type Check = { name: string; detail: string; state: 'checking' | 'ok' | 'warn' | 'error'; icon: string };
export default function SystemStatus() {
  const [checks, setChecks] = useState<Check[]>([{ name: 'Google Sheets API', detail: 'กำลังตรวจสอบการเชื่อมต่อ...', state: 'checking', icon: 'fa-solid fa-table-cells' }, { name: 'Telegram Notification', detail: 'ตรวจสอบ route แจ้งเตือน', state: 'checking', icon: 'fa-brands fa-telegram' }, { name: 'Offline Cache', detail: 'กำลังตรวจสอบพื้นที่จัดเก็บในเครื่อง', state: 'checking', icon: 'fa-solid fa-hard-drive' }]);
  useEffect(() => { let mounted = true; Promise.allSettled([fetchIncidents(), fetch('/api/notify', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ message: '' }) })]).then(async ([sheets, telegram]) => { if (!mounted) return; const telegramResponse = telegram.status === 'fulfilled' ? telegram.value : null; setChecks([{ name: 'Google Sheets API', detail: sheets.status === 'fulfilled' ? `เชื่อมต่อแล้ว · อ่านข้อมูลได้ ${sheets.value.length} รายการ` : 'ไม่สามารถเชื่อมต่อได้', state: sheets.status === 'fulfilled' ? 'ok' : 'error', icon: 'fa-solid fa-table-cells' }, { name: 'Telegram Notification', detail: telegramResponse?.status === 400 ? 'พร้อมใช้งาน · รอรับข้อความจากการบันทึกจริง' : telegramResponse?.status === 200 ? 'เชื่อมต่อและส่งได้' : 'ตรวจสอบ credentials หรือ endpoint', state: telegramResponse?.status === 400 || telegramResponse?.status === 200 ? 'ok' : 'warn', icon: 'fa-brands fa-telegram' }, { name: 'Offline Cache', detail: 'Local storage พร้อมใช้งานสำหรับ Draft ในอุปกรณ์นี้', state: 'ok', icon: 'fa-solid fa-hard-drive' }]); }); return () => { mounted = false; }; }, []);
  const styles = { checking: 'bg-slate-100 text-slate-500', ok: 'bg-emerald-100 text-emerald-700', warn: 'bg-amber-100 text-amber-700', error: 'bg-rose-100 text-rose-700' };
  return <div className="space-y-6"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-maroon-700">Governance</p><h2 className="mt-1 text-3xl font-bold tracking-tight text-slate-950">System Status</h2><p className="mt-2 text-sm text-slate-500">ตรวจสอบความพร้อมของบริการหลักที่ใช้ในระบบ</p></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="mb-5 flex items-center justify-between"><div><h3 className="text-lg font-bold text-slate-900">Service health</h3><p className="text-xs text-slate-400">อัปเดตอัตโนมัติเมื่อเปิดหน้านี้</p></div><span className="status-live"><span className="status-dot" /> Live</span></div><div className="divide-y divide-slate-100">{checks.map(check => <div key={check.name} className="flex items-center gap-4 py-4"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-slate-50 text-slate-600"><i className={check.icon} /></span><div className="min-w-0 flex-1"><p className="font-semibold text-slate-800">{check.name}</p><p className="mt-1 text-xs text-slate-400">{check.detail}</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${styles[check.state]}`}>{check.state === 'checking' ? 'กำลังตรวจ' : check.state === 'ok' ? 'พร้อมใช้งาน' : check.state === 'warn' ? 'ควรตรวจสอบ' : 'มีปัญหา'}</span></div>)}</div></div><div className="rounded-2xl border border-slate-200 bg-slate-50 p-5 text-sm text-slate-600"><i className="fa-solid fa-shield-halved mr-2 text-maroon-700" />ข้อมูล credentials ถูกประมวลผลฝั่ง server และไม่แสดงในหน้าเว็บ</div></div>;
}
